
#ifndef _TEMWORDLIST_H
#define _TEMWORDLIST_H

#include <string>
using namespace std;
const char* TEMWord[] = {
    "discrepancy n.差异，不符合，矛盾【例】The discrepancy in their ages didn't affect their love.年龄的差异并没有影响到他们的爱情",
    "discount v.怀疑地看待；漠视，低估；打折扣n.折扣【用】打折的固定说法：at 15% discount（打八五折）；discount of 30%（七折）",
    "celebrate v.庆祝；歌颂 Odysseus's heroic exploits are celebrated in The Odyssey.<<奥德赛>>史诗中歌颂了奥德修斯的丰功伟绩",
    "subject adj.隶属的，从属的，受支配的；有……倾向的，易受，常有vt.使隶属，使服从；使遭受，使经历【用】subject to，表示“易遭……的”之意",
    "absorb vt.吸收（水、热、光等）；吸引（注意），使专心，使全神贯注【用】be ~ed in，专心于某事【派】absorption n.吸收；专注；~ing adj.引人入胜的",
    "interchange v.交换，互换；交替发生n.交换，互换；立体交叉道【例】Interchange labor and repose during the work.工作中应该劳逸结合",
    "discretion n.谨慎；自由裁夺；酌处权【用】at the discretion of的意思是“由……斟酌决定”，但在句子中应看上下文来翻译或理解",
    "charm n.魅力，魔力 v.迷住，使……陶醉【派】charming（adj.迷人的，有魅力的；令人高兴的）",
    "smuggle v.走私，偷运【例】The man tried to smuggle something valuable through the customs.这名男子想从海关走私一些贵重物品",
    "orient vt.使适应；确定位置n.东方adj.[O-]东方的【用】“-oriented”，表示“以……为导向的”，如export-orientated（以出口为导向的）",
    "hospitality n.好客，殷勤的款待【例】Mary received them with her usual hospitality.玛丽以她惯常的殷勤好客接待了他们",
    "inform v.通知，告知，使了解；告密，告发【用】inform在表示“通知，告知”的时候，常与of或about搭配使用，而在表示“告发”时，常和against或on连用",
    "cruise v.巡航，游弋；旅行，漫游【派】cruiser（n.巡洋舰；有船舱的游艇）",
    "concept n.概念，观念，思想【派】conception（n.概念，理解；构想，看法；怀孕，妊娠）；conceptual（adj.概念的，观念的；抽象的）",
    "genius n.天才；天资，天赋【例】One is not born a genius；one becomes a genius.人生来并非天才，而是变成天才的",
    "linger v.逗留，徘徊【例】The incident was over, but the memory lingered on.事情是过去了，但记忆难以抹去",
    "invalid n.病人；残废者adj.无效的；作废的【例】Damaged or marked ballots were regarded as invalid.损坏或有标记的选票都被视为无效",
    "trail n.足迹，踪迹；小径，小路；（人流、车流等）一股，（烟、尘等）一缕v.拖，拖拽；跟踪，尾随；（植物）蔓生",
    "rear n.后部，背面 v.饲养，抚养，栽培【例】Alice reared the homeless boy as her own child.艾丽丝把这个无家可归的小男孩当亲生孩子抚养",
    "fake n.假货，赝品；骗人诡计adj.假的，冒充的v.伪造；假装；捏造【例】The painting was proved to be a fake.那幅画被证实是赝品",
    "marvel n.令人惊奇的事物 v.惊奇，惊异【派】marvelous（adj.很好的，妙极了的）",
    "crude adj.天然的，未加工的；粗野的，没有教养的；赤裸裸的n.原油【例】crude oil原油",
    "manual n.手册，指南 adj.手工的，用手的；体力的【例】Making these models requires manual skills.做这些模型需要手工技巧",
    "hysteric adj.歇斯底里的；有癔病的n.[-s]歇斯底里的发作【派】hysterical（adj.歇斯底里的；有癔病的） hysteria（n.歇斯底里症）",
    "interact vi.相互作用，相互影响【派】interaction（n.相互作用，相互影响）；interactive（adj.互相作用的，互相影响的；交互式的，人机对话的）",
    "ethnic adj.种族的，部族的，民族的【用】ethnic group 族群 ; 民族 ; 同种族同文化的民族 ; 同种同文化之民族；Ethnic Township 民族乡",
    "hammer n.锤，槌，榔头 v.用锤敲打，（反复）敲打；彻底击败【用】词组up to the hammer表示“第一流的，极好的”",
    "blaze n.火；光辉，灿烂；迸发，爆发v.燃烧，冒火焰；发光，放光彩；发怒【用】词组a/the blaze of表示“……的光芒；爆发”",
    "spoil v.损坏，糟蹋；宠坏，溺爱n.掠夺物，赃物【用】be spoiling for是spoil的常用搭配，意思是“很想，渴望”",
    "join v.连接，结合；与……一起做某事，与……会合；成为……的一员 n.连接处，结合点【用】join sth.to sth.“将……和……连接起来”；join up“从军”",
    "provided conj.以……为条件，假如【用】provided的意思是“假如，如果，以……为条件”，相当于on the condition that……",
    "provided conj.假如【例】Provided you have the courage to admit your mistakes, I will forgive you.假如你有勇气承认自己的错误，我就原谅你",
    "waste n.损耗，浪费；废物，废料；荒野，荒地 v.浪费，滥用；（使）身体消瘦（衰弱）；使荒芜adj.荒芜的，荒废的；无用的，废弃的",
    "hearty adj.热情友好的，衷心的；健壮的，精力充沛的；兴高采烈的 The heroes received a hearty welcome from the public.英雄们受到了群众的热烈欢迎",
    "motivate vt.促动，激发，作为……的动机【派】motivation〔n.动力，促动（激发）因素〕；motive（n.动机，目的）",
    "heave v.举起，拉，拖；投掷；（有节奏地）起伏【例】Lucia flushed with anger, and her bosom began to heave.露西娅气得脸通红，胸部开始有节奏地起伏",
    "frail adj.脆弱的，易损坏的，不坚实的；虚弱的；薄弱的【派】frailty（n.虚弱，脆弱）",
    "wipe v.抹，擦，去除【例】The new Chief Minister of the state promises to wipe out crime and corruption.该州的新任首席部长保证清除犯罪及腐败",
    "embarrass vt.使窘迫，使困扰，使为难；妨碍，牵累【派】embarrassing（adj.使人尴尬的，使人为难的）；embarrassment（n.窘迫，局促不安）",
    "wake v.醒来，唤醒n.（行船在水面留下的）航迹，尾流；守夜，守灵【用】wake sb.up，“唤醒，弄醒；使……奋起”的意思。in the wake of表示“随某事物之后到来”",
    "sufficient adj.足够的，充分的【派】sufficiency（n.足量，充足）",
    "sufficient 指“充分的”，较常用于书面语中，放在名词前；adequate表示“适当的；足够的”，强调相对于一个不太高的标准来说，如adequate food",
    "twist n./v.搓，捻，绞；转动，拧，扭；曲解；盘旋，迂回【用】twist and turn是“弯弯曲曲”的意思",
    "disclose v.（使）显露，揭露，泄露；公开，表明，说出【派】disclosure（n.揭发，透露；公开）",
    "discover是不为人所见、所知事物为众人知晓，暗指被发现的事物是很早之前就客观存在的，Columbus discovered America.；disclose指把有意隐藏的事物公之于众",
    /*长度不能超过上面这句长度不能超过上面这句长度不能超过上面这句长度不能超过上面这句长度不能超过上面这句长度不能超过上面这句长度不能超过上面这句长度不能超*/
    "curb n.勒马的链条（皮带）；控制；路缘v.给（马）装上勒马链，勒住（马）；控制，约束【用】词组keep a curb on表示“控制……”",
    "curb强调以突然、严厉的方式控制、抑制；restrain指使用某种强迫手段或通过劝说来约束或制止，常用搭配是restrain sb.from doing sth.",
    "inhibit vt. 抑制；禁止 强调抑制、控制某种情感、欲望等，如：Thirst inhibited the desire to eat",
    "ventilate vt.使通风【派】ventilation（n.空气流通；通风设备）；ventilator（n.通风设备，通风口）",
    "base n.基础，底层vt.把……设在，以……为基地adj.卑鄙的，下贱的【用】base常与介词on搭配，表示“以……为基础，以……为素材”",
    "base 【派】basic（adj.基本的，基础的；首要的）；basically（adv.基本上，根本上，从根本上说）；basics（n.基本因素，基本原理；概要）",
    "extent n.范围，广度；长度；程度，限度【用】to some extent 在一定程度上 ; 在某种程度上 ; 在必定水平上 ; 从一定程度上讲",
    "initiative n.进取心，首创精神；主动性adj.起始的，初步的【用】on one's own initiative意为“主动地”；take the initiative表示“采取主动，带头，发起”",
    "blame vt.责备，找……的差错；把……归咎，推诿n.责备，责怪；责任【用】表示“某人应受责备”时要用sb.be to blame，不用被动语态",
    "straight adj.笔直的；直接的；整齐的，端正的；正直的，坦率的，诚实的adv.笔直地；直接地",
    "straight 【派】straighten〔v.（使）挺直，纠正，改正；整理，清理；（使）好转，改进〕；straightforward（adj.诚实的，坦白的；易懂的，易做的）",
    "convince v.使确信，使信服；说服【派】convincing（adj.有说服力的，令人信服的）【派】convincing（adj.有说服力的，令人信服的）",
    "major n.（陆军或美空军）少校；主修的专业vi.（大学里）主修adj.主要的，重要的 【用】major作动词表示“主修”，“主修某个专业”要用major in",
    "graduate v.毕业；取得资格n.毕业生adj.毕了业的；研究生的【派】graduation（n.毕业；毕业典礼）",
    "suspicion n.怀疑，猜疑，嫌疑，疑心【用】on suspicion 因嫌疑；根据猜想；on suspicion of 有嫌疑；with suspicion 怀疑地；under suspicion 受嫌疑",
    "logic n.逻辑（学），逻辑性【派】logical（adj.符合逻辑的，逻辑上的）",
    "foretell v.预言，预测【辨】foretell与foresee相似，都表预知未来，与正确与否无关；forecast强调通过某些数据、信息来推测预报，如：weather forecast",
    "notorious adj.臭名昭著的，声名狼藉的【例】The mayor is notorious for his bribery and corruption.这位市长由于贪污受贿而臭名昭著",
    "strangle v.扼死，勒死；抑制，扼杀【例】Isabel tried her best to strangle the unspeakable agony.伊莎贝尔竭力抑制那无法言表的痛苦",
    "prudent adj.谨慎的，精明的【例】The voters say they want low taxes and prudent spending cuts.选民表示他们想要低税收和审慎的开支削减",
    "commute v.定时往返两地；减轻（刑罚）；用……交换；改变（付款）方式【例】In a big city, people need commute by bus.在大城市，人们需要乘公车上下班",
    "sane adj.心智健全的，神志正常的；明智的，稳健的【派】sanity（n.神志正常，心智健康；明智，理智）",
    "cancel v.取消；删去，省略，划掉",
    "account n.账，账目，账户；报道，记载，叙述；理由【用】on account of在意思上相当于due to和because of【派】accountant（n.会计师，会计）",
    "flexible adj.柔韧的，易弯曲的；可变通的，灵活的；易适应的【派】flexibly（adv.灵活地）；flexibility（n.灵活性，机动性；柔韧性）",
    "sigh v.叹息，叹气n.叹息，叹气声【例】Tom thinks that man shouldn't sigh or cry for love.汤姆认为男人不应该为爱情叹息和哭泣",
    "fantasy n.想象，幻想【用】fantasy后面可以接about sth.，意为“关于……的幻想”【派】fantastic（adj.极好的，美妙的；不切实际的，异想天开的；古怪的）",
    "offset n.分支，旁支；补偿，抵消v.补偿，抵消【记】来自词组set off（抵消）",
    "dim adj.暗淡的，昏暗的；朦胧的；迟钝的，愚蠢的v.（使）变暗淡；（使）变模糊，（使）失去光泽【辨】dim强调由于光线或清晰度减弱而导致无法看清某物",
    "confess v.供认，坦白，承认；忏悔（罪恶等）【用】confess后一般接介词to，表示“承认……”【派】confession（n.忏悔，认错，招供）",
    "delegate n.代表，代表团成员v.授权，委托，委派……为代表【派】delegation（n.代表团；委派）",
    "hover vi.飞翔，盘旋，徘徊【用】hover可以用来表示鸟等盘旋，也可以表示人徘徊、走来走去",
    "feast n.盛宴，宴会v.盛宴款待；使（感官等）得到享受",
    "twinkle v.闪烁，闪耀；（指眼睛）闪亮，眨眼n.闪烁，闪光；闪亮，闪动【记】儿歌“twinkle, twinkle, little star”",
    "untie vt.解开，松开 The small chimp struggled to untie the ropes of the cage, but to no avail.小黑猩猩挣扎着想解开笼子上的绳索，但只是徒劳",
    "surge vi.在浪涛中前进；急剧上升n.向前或向上的运动；突然发生，激增",
    "skip v.轻快地跳，跳跃；跳绳；跳过，略去",
    "spark n.火星，火花，电花v.发出火花，闪出电花；导致，引起 Rubbing stones together produces sparks to start a fire.摩擦石头可产生火花用来引火",
    "diagnose vt.诊断（疾病）；判断，调查分析（问题等的）原因（性质）【派】diagnosis〔n.诊断（结论）；调查，判断〕；diagnostic（adj.诊断的；判断的）",
    "fluent adj.流畅的，流利的【派】fluency（n.流利，流畅）",
    "glide n./v.滑动，滑行；滑翔【派】glider（n.滑翔机）",
    "approve v.批准，通过；赞成，称许【用】approve作“赞成”讲时一定要与of连用【派】approval（n.赞成；认可，批准）",
    "measure n.度量，量度单位；标准；尺度；(-s)措施，办法；程度，范围v.测量；有……长（或宽、高等）【派】measurement〔n.测定；（量得的）尺寸，大小〕",
    "absurd adj.不合理的，荒谬的，可笑的【用】absurd后面的从句中一般用“should+动词原形”",
    "stab v.刺，戳，刺入；产生刺痛n.刺，戳；刺痛，伤痛",
    "string n.细绳，带子；乐器的弦；以线串成之物，一串v.缚，扎，穿；上弦",
    "predict v.预言，预测【用】predict常用的句型是It's predicted that……，意思是“预计……”【派】prediction（n.预言；被预言的事物）",
    "enquire v.调查；询问，打听【用】enquire是inquire的变体，enquire after表示“问候，询问身体状况”；若要表示“打听某事”，则用enquire upon/into sth.",
    "multiply v.使相乘；增多；繁殖，增殖【例】Friendships multiply joys and divide grief.友谊增加快乐，分担痛苦",
    "infect vt.传染；感染；影响【派】infection〔n.传染（病）；影响〕；infectious（adj.传染性的；有感染力的）",
    "quantity n.量，数量；分量，额；大量【派】quantitative（adj.数量的，定量的）；quantify（v.量度；确定数量；量化）",
    "unanimous adj.一致同意的，一致通过的【例】Then there was a unanimous call for an explanation.随后人们一致要求得到解释",
    "torment n.痛苦，折磨；令人痛苦或烦恼的人或物vt.使痛苦，使烦恼；折磨【辨】torment指精神上处于长期的烦恼或痛苦中；torture指身体或精神受到巨大痛苦",
    "venture n.（尤指有风险的）企业，商业，经营项目v.冒险；敢于，胆敢【例】Nothing ventured, nothing gained.不入虎穴，焉得虎子",
    "contract n.契约，合同v.订立合约，签订合同；（使）收缩；得病，感染疾病【派】contraction（n.收缩，缩小；缩略字）；contractor（n.承包商，承建商）",
    "interrupt v.打断，打扰；中止，中断，阻碍【辨】interrupt, bother, disturb, interfere",
    "stoop v.俯身，弯腰；降格，卑屈n.弯腰，曲背；降格，卑屈",
    "shallow adj.浅的；浅薄的，肤浅的【例】Two girls had a shallow talk.这两个女孩的谈话很肤浅",
    "rid vt.使摆脱，使去掉，使获自由【用】get rid of比较常见，意思是“摆脱，解脱；赶走，清除”",
    "frequency n.次数，频率；频繁，屡次；周率",
    "enchant vt.用魔法迷惑，使着魔；使入迷，使陶醉 Linda was plainly enchanted by the view.琳达显然被这种景色陶醉了【用】多指由于喜悦或魔法而着迷",
    "comment n./v.评价，评论【派】commentary〔n.（对书籍等的）评语，评注，评论；实况报道〕；commentator（n.注释者，解说者；实况转播评论员，新闻广播员）",
    "outstanding adj.杰出的，优秀的；未付款的；（问题）未解决的",
    "release vt.释放，免除；放出，发射；发行，发表，发售n.释放，免除；放出，发射 The prisoner was ~d from jail when his sentence was up.囚犯刑满释放",
    "wretched adj.可怜的，悲惨的；恶劣的，令人讨厌的【例】wretched news不幸的消息",
    "stifle v.使窒息，窒闷；熄灭，扑灭；抑制，遏止【例】The smoke in the room stifled the children.房间里的烟使得孩子们窒息",
    "solve v.解决，解答，解释【辨】solve指解决具体问题，如：solve the question；resolve指解决抽象的问题或困难，如：resolve the difficulty",
    "reckless adj.轻率的，鲁莽的，不计后果的 It is a ~ and irresponsible attack, bordering on the libelous.这是轻率而不负责任的抨击，和诽谤差不多",
    "hoarse adj.（声音）沙哑的 The voice of the cheerleaders sometimes becomes ~ because they shout and yell.拉拉队员们的声音有时会因为叫喊变得沙哑",
    "duration n.持续（时间）【用】固定搭配for the duration意思是“在整段时间内”",
    "moan n.呻吟（声），呜咽（声）；抱怨v.呻吟；抱怨【例】We moaned and complained about how unfair it was.我们抱怨这是多么的不公平",
    "responsible adj.责任的，应负责的；可靠的，可信赖的；（指职位）责任重大的【用】be ~ for 对……负责【派】responsibility（n.责任，负责；职责，任务）",
    "yearn vi.想念，思慕，渴望【用】yearn为不及物动词，常与for搭配，表示“渴望……”",
    
};
#define TEMWordCount (sizeof(TEMWord)/sizeof(char *)) 
#endif